export const IMAGES = {
  startScreenBg: require("../../../assets/images/startScreenBg.png"),
  homeActive: require("../../../assets/images/homeActive.png"),
  homeInactive: require("../../../assets/images/homeInactive.png"),
  newsActive: require("../../../assets/images/newsActive.png"),
  newsInactive: require("../../../assets/images/newsInactive.png"),
  profile: require("../../../assets/images/profile.png"),
  profileActive: require("../../../assets/images/profileActive.png"),
  logo: require("../../../assets/images/logo.png"),
  search: require("../../../assets/images/search.png"),
  ads: require("../../../assets/images/ads.png"),
  moreWatching: require("../../../assets/images/moreWatching.png"),
  moreWatchingFlatList: require("../../../assets/images/moreWatchingFlatList.png"),
  moreWatchingFlatList1: require("../../../assets/images/moreWatchingFlatList1.png"),
  moreWatchingFlatList2: require("../../../assets/images/moreWatchingFlatList2.png"),
  clock: require("../../../assets/images/clock.png"),
  like: require("../../../assets/images/like.png"),
  dislike: require("../../../assets/images/dislike.png"),
  more: require("../../../assets/images/more.png"),
  lastNews: require("../../../assets/images/lastNews.png"),
  mainCard: require("../../../assets/images/mainCard.png"),
  note: require("../../../assets/images/note.png"),
  ball: require("../../../assets/images/ball.png"),
  share: require("../../../assets/images/share.png"),
  congress: require("../../../assets/images/congress.png"),
  subNews: require("../../../assets/images/subNews.png"),
  moreDark: require("../../../assets/images/moreDark.png"),
};
